### ISSUE TITLE
Add a ShowGrid and Anchors option

### ISSUE THREAD

**Issue by tznind** [gui-cs/TerminalGuiDesigner#86]
> What can be done is redraw the dots on the Editor if a flag `ShowGrid` is enabled.

_Originally posted by @BDisp in https://github.com/gui-cs/TerminalGuiDesigner/issues/63#issuecomment-1235335444_

![image](https://user-images.githubusercontent.com/31306100/188137665-aa238b23-d929-4aee-826d-2f1b5cf33f14.png)
_(Screenshot is from linked issue)_

If I understand correctly this is a request to show dots for each pixel square of the console where there is not content already drawn there in a View being edited.

Also to draw 'anchors' at the corners of container controls (possibly over the top of any existing content)

**Comment by BDisp** [comment]
> If I understand correctly this is a request to show dots for each pixel square of the console where there is not content already drawn there in a View being edited.

Yes, but you can draw the dots on all the container first and then redraw the views added. Something like instead of clearing the container with a space ' ', clearing using a dot '.'. Then redraw the added views. The dots is only show at design time, of course.
Another way is creating a custom view with the dots that fit all the container and send to back of others views. Of course this view cannot be add to the running source app, but only in the Editor. I think this is the best option because you don't need to override the container view to clear all the area with a dot.

> Also to draw 'anchors' at the corners of container controls (possibly over the top of any existing content)

Yes only when the view is focused.
